### PR TITLE
magisk: All updated to 26404

### PR DESCRIPTION
**Pull request by sekaiacg**
fix https://github.com/bmax121/APatch/issues/163#issuecomment-1899175010

### CODE REVIEW

**Comment by osm0sis** [comment]
Thanks! But where did these come from? None of the sizes or checksums match the official Magisk Debug Canary or Magisk Release Canary builds. 🤔

**Comment by sekaiacg** [comment]
> Thanks! But where did these come from? None of the sizes or checksums match the official Magisk Debug Canary or Magisk Release Canary builds. 🤔
> 
> Wouldn't it be wise to use the official Debug builds except for where standalone is required (resetprop)?

Compile from source code and strip.
https://github.com/topjohnwu/Magisk/commit/86e00209649a60e5359ace3665997b653e00fc33

`./build.py -rv binary resetprop magiskpolicy busybox magiskboot`
`$ONDK/bin/llvm-strip -s -g resetprop magiskpolicy busybox magiskboot`

**Comment by sekaiacg** [comment]
Example from ksu: https://github.com/tiann/KernelSU/commit/153ce9a39a25d1e3556d2711e92026d36b9405cf

**Comment by ponces** [comment]
> Thanks! But where did these come from? None of the sizes or checksums match the official Magisk Debug Canary or Magisk Release Canary builds. 🤔
> 
> Wouldn't it be wise to use the official Debug builds except for where standalone is required (resetprop)?

I agree with this. Can you just push resetprop update?

**Comment by osm0sis** [comment]
> I agree with this. Can you just push resetprop update?

I'd say make it the exact build KSU is using too, so things are completely in sync. 🙌

**Comment by osm0sis** [comment]
#175 has this handled, this one can be closed. 👍

**Pull request closed without merging**
