### PR TITLE
New icon

### PR DESCRIPTION
**Pull request by Traaanaelle**

### CODE REVIEW

**Comment by ponces** [comment]
Isn't this missing those vector drawables at `res/drawable`?

**Comment by ravindu644** [comment]
> Isn't this missing those vector drawables at `res/drawable`?

Hi, can we add a Change language button in the apatch manager ? Current setup only changes the language with device's one.

**Comment by Traaanaelle** [comment]
https://github.com/bmax121/APatch/pull/79#issuecomment-1884682880
sorry i did it in a rush on my phone, i'll review it when i have access to my pc

**Comment by Traaanaelle** [comment]
https://github.com/bmax121/APatch/pull/79#issuecomment-1884682880

> > Isn't this missing those vector drawables at `res/drawable`?
> 
> Hi, can we add a Change language button in the apatch manager ? Current setup only changes the language with device's one.

U can use this app
https://github.com/VegaBobo/Language-Selector

**Comment by ravindu644** [comment]
> > Hi, can we add a Change language button in the apatch manager ? Current setup only changes the language with device's one.
> 
> U can use this app https://github.com/VegaBobo/Language-Selector

No, I meant a "change language button" 😶

We translated app, but lot of people in our country, uses english as their primary language in phones because sinhala translation sucks in android.

**Comment by ravindu644** [comment]
> > Hi, can we add a Change language button in the apatch manager ? Current setup only changes the language with device's one.
> 
> U can use this app https://github.com/VegaBobo/Language-Selector

btw that app also helps

**Pull request closed without merging**
