### PR TITLE
feat: hide bottom pages that need su if apd is not installed

### PR DESCRIPTION
**Pull request by ponces**

### CODE REVIEW

**Comment by marat2509** [comment]
Any screen/video?

**Comment by ponces** [comment]
> Any screen/video?

Sure!

https://github.com/bmax121/APatch/assets/4687488/3707963a-fabc-4a12-86b3-4c100cbd340e

**Comment by marat2509** [comment]
Not considered is that even when AndroidPatch is not installed, root rights can still be obtained (more often via running /system/bin/kp) by adding the app to the su list beforehand. Also the kp modules tab should not be hidden if kpatch is installed.

**Comment by ponces** [comment]
> Not considered is that even when AndroidPatch is not installed, root rights can still be obtained (more often via running /system/bin/kp) by adding the app to the su list beforehand. Also the kp modules tab should not be hidden if kpatch is installed. 

This is a bit inspired by what ksu does too.
You're right but I was considering the state of apatch for this. I can easily consider su access if provided by kp.
I'll update it later, thanks for the suggestions.

**Comment by ponces** [comment]
Ok, so this is the current states scenario:
- Home -> always available, no state dependency
- KModule -> available on all states besides the "unknown" state which means `kpatch` not installed
- SuperUser -> only available if `su` exists
- AModule -> only available if `apatch` is installed ("ready" or "needing update")

**Comment by marat2509** [comment]
> * SuperUser -> only available if `su` exists
Only available when kpatch installed.

Try: delete AndroidPatch, clear su list, open termux/terminal, enter `/system/bin/kp`, not working? is ok (because app isn't in su list), add termux/terminal to su list, try again.

**Comment by ponces** [comment]
> > * SuperUser -> only available if `su` exists
> 
> Only available if kpatch is installed.
> 
> Try: uninstall AndroidPatch, clear the su list, open termux/terminal, type `/system/bin/kp`, doesn't work? everything is fine (because the app is not in the su list), add termux/terminal to the su list, try again.

So you mean that both "KModule" and "SuperUser" pages should benefit from the same conditions which is "if kpatch is installed". Is this correct?

**Comment by marat2509** [comment]
> should benefit from the same conditions which is "if kpatch is installed". Is this correct?

Yes.

**Comment by ponces** [comment]
I added some tasks for vscode to easily built this by a shortcut but I can remove if you agree to be useless for the dev community

**Pull request merged**
