### PR TITLE
Revert "Translations update from Hosted Weblate for App"

### PR DESCRIPTION
**Pull request by marat2509**
Reverts bmax121/APatch#273

### CODE REVIEW

**Comment by pomelohan** [comment]
? I had fixed this morning. So there’s no need to revert brother.

**Comment by Admirepowered** [comment]
Wtf are you doing

**Comment by marat2509** [comment]
I beg your pardon. I really didn't notice. I expected that if there were any changes about that merge request, github would say that the merge can't be done automatically.

So what we're doing is revert to revert...?
Would @bmax121 be better off doing git reset --hard ...; git push -f?

**Comment by pomelohan** [comment]
https://github.com/bmax121/APatch/commit/59f061f59abbd975acb6f111741f970aee7da0f4

Fixed this morning. Please **wait for review** next time before merging please! Thank you!

**Comment by bmax121** [comment]
@Admirepowered Be polite please

**Comment by pomelohan** [comment]
> I beg your pardon. I really didn't notice. I expected that if there were any changes about that merge request, github would say that the merge can't be done automatically.
> 
> So what we're doing is revert to revert...? Would @bmax121 be better off doing git reset --hard ...; git push -f?

I will fix it later. Don’t worry. Just be careful next time bro

**Comment by Admirepowered** [comment]
> I beg your pardon. I really didn't notice. I expected that if there were any changes about that merge request, github would say that the merge can't be done automatically.
> 
> So what we're doing is revert to revert...? Would @bmax121 be better off doing git reset --hard ...; git push -f?

You don't see that commit on you pull request,and you are deliberate？

**Comment by Admirepowered** [comment]
Before merge, at least ask others,ok？

**Pull request merged**
