### PR TITLE
Add AOSP recovery support & Detect kernel configuration & Various bug fixes

### PR DESCRIPTION
**Pull request by SakuraKyuo**
Change Apatch  ->  APatch

### CODE REVIEW

**Comment by SakuraKyuo** [comment]
In commit https://github.com/bmax121/APatch/pull/583/commits/15bb04bc43769ebc6049dfe028e864eab08581df, we have already support flash APatch in AOSP Based Recovery

After Android 11, the AOSP-based Recovery no longer has /sbin, while TWRP and LineageOS-based Recovery retain the /sbin/sh interpreter to provide compatibility with this shell flashing script. TWRP also adds bash to /sbin.

In order to adapt to AOSP-Based Recovery, we canceled the use of /sbin/bash to run the installation script, and instead used APatch's built-in busybox to run the installation script to achieve the purpose of adapting to all recovery.

We don't need updater-script anymore, so keep it empty. The core part is in update-binary and addon folder.

**Comment by SakuraKyuo** [comment]
In commit https://github.com/bmax121/APatch/pull/583/commits/19857de95173a5a9f7d15e2518faefc2a2d52055, we have switch to a more reliable way to get log

Previously, we used to output logs directly to /dev/tmp/install/log, but after multiple rounds of testing, this method only obtains the previous line log of the core error, which brings inconvenience to development work troubleshooting, so we changed the acquisition method.

However, due to unknown reasons, the core error may be output at the beginning of the log output (i.e. the first line). Therefore, when the user feedback patch failed, we need to ask for the user to provide a screenshot of the starting position to determine the core error.

**Comment by SakuraKyuo** [comment]
In commit https://github.com/SakuraKyuo/APatch/commit/b35bbfae51cf4c545ceb7ecffcf23e1d236d771a, Install & Uninstall script has already moved to assets folder

In order to further simplify the apk, the scripts has been moved to the assets folder without affecting its normal operation.

**Comment by SakuraKyuo** [comment]
In commit https://github.com/SakuraKyuo/APatch/commit/626b9124c66050efb28c352c3d01d7f6410c474c, add kernel flag detection.

According to the APatch documentation, the APatch patch requires setting the kernel flag CONFIG_KALLSYMS to y (i.e. enabling the kernel flag). kptools will report an error "analyze_kallsyms_info error" and exit because CONFIG_KALLSYMS is not enabled.

In order to intercept this problem at the initial stage of installation and reduce the workload of developers, extract-ikconfig provided by https://github.com/torvalds/linux was added. The flashing script will obtain whether the kernel flag is turned on. If it is turned off, the installation script will abort and return an error message to the user.

**Comment by pomelohan** [comment]
@gooroodev review

**Comment by gooroodev** [comment]
## Please double check the following review of the pull request:


### Issues counts

| 🐞Mistake | 🤪Typo | 🚨Security | 🚀Performance | 💪Best Practices | 📖Readability | ❓Others |
|:--------:|:------:|:----------:|:-------------:|:----------------:|:-------------:|:--------:|
|    0     |    1   |      0     |       0       |         1        |       1       |    0     |

### Changes in the diff

- ✅ Corrected shebang from `#!/sbin/bash` to `#!/bin/sh` in several scripts.
- 📖 Improved readability by changing `Apatch` to `APatch` in `InstallAP.sh`.
- ➕ Added a new script `extract-ikconfig`.
- ➕ Added a new function `kernelFlagsErr` in `InstallAP.sh`.
- ➕ Added checks for `CONFIG_KALLSYMS` in `InstallAP.sh`.
- 🛠️ Changed the destination directory from `addon` to `assets` in `build.gradle.kts`.
- 🛠️ Updated `update_binary.sh` to reflect the new directory structure.
- ➖ Removed redundant lines from `update_script.sh`.

### Identified Issues

| ID  | Type            | Details                                                                 | Severity | Confidence |
|-----|-----------------|-------------------------------------------------------------------------|----------|------------|
| 1   | 🤪Typo          | Typo in `InstallAP.sh`: "NOT enable it" should be "NOT enabled it".     | 🟡Low    | 🟡Low      |
| 2   | 💪Best Practices| Use `$(...)` instead of backticks for command substitution in `extract-ikconfig`. | 🟠Medium | 🟠Medium   |
| 3   | 📖Readability   | Missing newline at the end of `extract-ikconfig`.                        | 🟡Low    | 🟡Low      |

### Issue 1: Typo in `InstallAP.sh`

#### Explanation
There is a typo in the error message in the `kernelFlagsErr` function. The message "But your kernel seems NOT enable it." should be "But your kernel seems NOT enabled it."

#### Fix
```diff
 function kernelFlagsErr(){
-	ui_print "- Installation has Aborted!"
-	ui_print "- APatch requires CONFIG_KALLSYMS to be Enabled."
-	ui_print "- But your kernel seems NOT enable it."
+    ui_print "- Installation has Aborted!"
+    ui_print "- APatch requires CONFIG_KALLSYMS to be Enabled."
+    ui_print "- But your kernel seems NOT enabled it."
    exit
}
```

#### Explanation of the Fix
Corrected the typo by changing "enable" to "enabled".

### Issue 2: Use `$(...)` instead of backticks for command substitution in `extract-ikconfig`

#### Explanation
Using `$(...)` for command substitution is preferred over backticks because it is more readable and can be nested more easily.

#### Fix
```diff
 dump_config()
 {
-    if	pos=`tr "$cf1\n$cf2" "\n$cf2=" < "$1" | grep -abo "^$cf2"`
+    if	pos=$(tr "$cf1\n$cf2" "\n$cf2=" < "$1" | grep -abo "^$cf2")
    then
        pos=${pos%%:*}
        tail -c+$(($pos+8)) "$1" | zcat > $tmp1 2> /dev/null
        if	[ $? != 1 ]
        then	# exit status must be 0 or 2 (trailing garbage warning)
            cat $tmp1
            exit 0
        fi
    fi
}
```

#### Explanation of the Fix
Replaced backticks with `$(...)` for command substitution.

### Issue 3: Missing newline at the end of `extract-ikconfig`

#### Explanation
A newline at the end of the file improves readability and is a best practice.

#### Fix
```diff
 exit 1
-\ No newline at end of file
+ 
```

#### Explanation of the Fix
Added a newline at the end of the file.

### Missing Tests

#### Test for `extract-ikconfig` script

```sh
#!/bin/sh

# Test extract-ikconfig script
test_extract_ikconfig() {
    # Create a dummy kernel image with CONFIG_IKCONFIG enabled
    echo "IKCFG_ST\037\213\010CONFIG_IKCONFIG=y" > dummy_kernel.img

    # Run the extract-ikconfig script
    ./scripts/extract-ikconfig dummy_kernel.img > extracted_config

    # Check if the extracted config contains the expected content
    if grep -q "CONFIG_IKCONFIG=y" extracted_config; then
        echo "Test passed: CONFIG_IKCONFIG found in extracted config"
    else
        echo "Test failed: CONFIG_IKCONFIG not found in extracted config"
    fi

    # Clean up
    rm dummy_kernel.img extracted_config
}

test_extract_ikconfig
```

#### Explanation of the Test
This test creates a dummy kernel image with `CONFIG_IKCONFIG` enabled, runs the `extract-ikconfig` script, and checks if the extracted config contains the expected content.

--
I **only** arrive when I am mentioned and asked to review the pull request.
React or reply to share your feedback with me!

**Comment by pomelohan** [comment]
Also, `exclude` list in last commit modified should be restored to `**`

PR’s title should be also updated.

Thank you for you contribution 🌹

**Review by pomelohan — CHANGES_REQUESTED** [review]
I will switch to Approve after you finishing everything.

**Comment by SakuraKyuo** [comment]
In commit https://github.com/bmax121/APatch/pull/583/commits/7e67503bac012880d4abef5e989858fa4b01c26d, I have add kernel configuration detection when patching in APP 

Same as the commit https://github.com/SakuraKyuo/APatch/commit/626b9124c66050efb28c352c3d01d7f6410c474c, according to the documentation, enabling this kernel configuration is required. So the same detection method as the commit is used to detect kernel configuration when using apk to patch the kernel.

At the same time, since the grep command provided by busybox lacks the parameters the script need, toybox is also introduced to make the grep command in extract-ikconfig work.

**Comment by SakuraKyuo** [comment]
Force-pushed commit https://github.com/sakurakyuo/APatch/commit/a3282efab255b54cf79a3591076d4c8f2f689386 for fix flashing issue in recovery.

Because of `./` before `toybox`, it cannot be used in recovery, but patching the image in APP works normally. Remove it and everything working now.

**Comment by SakuraKyuo** [comment]
> Also, `exclude` list in last commit modified should be restored to `**`
> 
> PR’s title should be also updated.
> 
> Thank you for you contribution 🌹

With my test again, if restore to `**`, the scripts that use to flash in META-INF won't be pack into APK, so it should be keep not restore to `**`

**Comment by SakuraKyuo** [comment]
> I will switch to Approve after you finishing everything.

Everything are done.

**Review by marat2509 — APPROVED** [review]

**Comment by pomelohan** [comment]
> > I will switch to Approve after you finishing everything.
> 
> Everything are done.

Checked, but where does the toybox come from? F-droid policy requires every binary could be compiled from source. What's more, why should we use custom toybox instead of system one? Maybe can adapt to busybox? 😃

**Comment by SakuraKyuo** [comment]
> > > I will switch to Approve after you finishing everything.
> > 
> > 
> > Everything are done.
> 
> Checked, but where does the toybox come from? F-droid policy requires every binary could be compiled from source. What's more, why should we use custom toybox instead of system one? Maybe can adapt to busybox? 😃

In Force-pushed commit https://github.com/SakuraKyuo/APatch/commit/b4db07010adbc19643a2a819a0d67ac745193209, I have remove introduced toybox and intead of system toybox. As what you said, I shouldn't introduced a custom toybox to instead of system one, but now with my test, it works well with using system one

and in Force-pushed commit https://github.com/SakuraKyuo/APatch/commit/d50fa6f54670dd046a639aee94ebdbf36e7d2f5b, just fixed typo.

**Review by pomelohan — APPROVED** [review]

**Comment by pomelohan** [comment]
LGTM

**Pull request merged**
