### PR TITLE
feat(Home): add state icons

### PR DESCRIPTION
**Pull request by ponces**

### CODE REVIEW

**Comment by bmax121** [comment]
Do you have any screenshots of the state icons

**Comment by ponces** [comment]
> Do you have any screenshots of the state icons

Yeah! They are pretty similar to what KernelSU has but I can adjust them if you prefer any other preference :)

**Comment by ponces** [comment]
any change needed?

**Comment by marat2509** [comment]
> any change needed?

Is it possible to add minimal animation for these icons? At least appearances/changes, otherwise they change soullessly

**Comment by ponces** [comment]
> > any change needed?
> 
> Is it possible to add minimal animation for these icons? At least appearances/changes, otherwise they change soullessly

I would say it's a bit out of scope of this PR but I can take a look at it after this is merged, yeah

**Pull request merged**
